import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        gold: {
          50: "#fdf9ec",
          100: "#faf0cd",
          200: "#f5df9b",
          300: "#eecb64",
          400: "#e5b23a",
          500: "#d4a017",
          600: "#b3830f",
          700: "#8f660e",
          800: "#755314",
          900: "#624616",
          950: "#392509",
        },
        // LG landing page (Stitch design) tokens — dark-only palette
        "on-secondary": "#3d2e00",
        "surface-variant": "#353439",
        "on-background": "#e4e1e7",
        "on-error": "#690005",
        "on-primary-container": "#7b797c",
        "secondary-fixed": "#ffe08e",
        "on-secondary-fixed": "#241a00",
        "secondary-fixed-dim": "#ecc246",
        "on-surface-variant": "#c8c5ca",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "inverse-primary": "#5f5e60",
        "surface-container-highest": "#353439",
        "surface-container-lowest": "#0e0e12",
        "primary-fixed": "#e5e1e4",
        "inverse-surface": "#e4e1e7",
        "outline-variant": "#47464a",
        "secondary-container": "#b18c09",
        outline: "#919095",
        "tertiary-fixed": "#e2e2e2",
        surface: "#131317",
        "on-tertiary": "#2f3131",
        tertiary: "#c6c6c7",
        background: "#131317",
        secondary: "#ecc246",
        "surface-container": "#1f1f23",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#584400",
        "surface-bright": "#39393d",
        "surface-dim": "#131317",
        "tertiary-container": "#0a0c0c",
        "on-primary": "#313032",
        primary: "#c8c6c8",
        "primary-container": "#0b0b0d",
        "on-secondary-container": "#352800",
        "inverse-on-surface": "#303034",
        "on-tertiary-container": "#797a7a",
        "surface-tint": "#c8c6c8",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-low": "#1b1b1f",
        error: "#ffb4ab",
        "on-surface": "#e4e1e7",
        "primary-fixed-dim": "#c8c6c8",
        "surface-container-high": "#2a2a2e",
        "on-primary-fixed": "#1c1b1d",
        "on-primary-fixed-variant": "#474649",
      },
      spacing: {
        gutter: "24px",
        unit: "4px",
        "container-max": "1440px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "display-lg": ["var(--font-inter)"],
        "label-caps": ["var(--font-jetbrains-mono)"],
        "display-lg-mobile": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "data-point": ["var(--font-jetbrains-mono)"],
        "headline-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.2em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "data-point": ["14px", { lineHeight: "1.0", letterSpacing: "0em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-right": {
          "0%": { transform: "translateX(100%)" },
          "100%": { transform: "translateX(0)" },
        },
        "slide-in-left": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.4s ease-out both",
        "fade-in-up": "fade-in-up 0.45s ease-out both",
        "slide-in-right": "slide-in-right 0.3s ease-out both",
        "slide-in-left": "slide-in-left 0.3s ease-out both",
      },
    },
  },
  plugins: [],
};

export default config;
